apiVersion: apps/v1

kind: Deployment

metadata:
  name: kubernetes-demo-deployment
  labels:
    app: kubernetes-demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
        - name: kubernetes-demo
          image: stefanoboriero/kubernetes-demo
          ports:
            - name: kubernetes-demo
              containerPort: 8080
