apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
spec:
  type: NodePort
  selector:
    app: kubernetes-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
      name: http
  clusterIP: 10.100.184.41
